services:
  # Backend (Spring Boot)
  - type: web
    name: kodder-backend
    env: java
    buildCommand: ./gradlew build
    startCommand: ./gradlew bootRun
    plan: free
    envVars:
      - key: PORT
        value: 8080

  # Frontend (React + Vite)
  - type: web
    name: kodder-frontend
    env: node
    buildCommand: yarn && yarn build
    startCommand: yarn preview --port 10000
    plan: free
    envVars:
      - key: PORT
        value: 10000
